#!/usr/bin/env python3
"""Renders the progress board from docs/progress.json.

    python3 tools/progress.py            # writes docs/PROGRESS.md + docs/progress.html
    python3 tools/progress.py --serve    # ... and serves it on http://localhost:8111/

The JSON is the single source of truth: it is the only file edited by hand, and
the two generated files are what the user reads (one in the repository, one in a
browser). Nothing here talks to the network or to Premiere.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "progress.json"
MD = ROOT / "docs" / "PROGRESS.md"
HTML = ROOT / "docs" / "progress.html"

# done is worth everything, partial half, todo/blocked nothing. "impossible" rows
# are excluded from the arithmetic (they are permanent, not pending) but are still
# rendered, so the board never quietly drops a requirement.
CREDIT = {"done": 1.0, "partial": 0.5, "impossible": None}
STATUS_LABEL = {
    "done": "done",
    "partial": "in progress",
    "todo": "to do",
    "blocked": "waiting on a decision",
    "impossible": "not possible",
    "user": "needs your machine",
}
CLASS_LABEL = {
    "A": "native, shipped",
    "B": "native, planned",
    "C": "closest possible",
    "D": "not attempted",
}


def phase_progress(phase: dict) -> tuple[float, int, int]:
    """Weighted completion of one phase: (fraction, weight counted, items counted)."""
    total = 0.0
    earned = 0.0
    counted = 0
    for item in phase["items"]:
        credit = CREDIT.get(item["status"], 0.0)
        if credit is None:
            continue
        weight = float(item.get("weight", 1))
        total += weight
        earned += weight * credit
        counted += 1
    if total == 0:
        return 1.0, 0, counted
    return earned / total, int(total), counted


def bar(fraction: float, width: int = 26, filled: str = "#", empty: str = ".") -> str:
    done = int(round(fraction * width))
    return filled * done + empty * (width - done)


def markdown(data: dict, computed: dict, stamp: str) -> str:
    out: list[str] = []
    out.append("# Azy Skin — implementation progress\n")
    out.append(f"*Generated from `docs/progress.json` by `tools/progress.py` on {stamp}. "
               "Do not edit this file by hand.*\n")
    out.append("Against: the Complete Implementation Specification (50 sections). "
               "Class A = native and shipped, B = native and planned, "
               "C = the closest possible treatment (the element itself is out of reach), "
               "D = needs injection and is not attempted. "
               "See [`FEASIBILITY.md`](FEASIBILITY.md) for why each row lands where it does.\n")

    overall = computed["overall"]
    out.append("```")
    out.append(f"overall  [{bar(overall, 32)}] {overall * 100:5.1f}%   "
               f"remaining ≈ {computed['eta_total']}")
    out.append("")
    for phase in computed["phases"]:
        out.append(f"{phase['id']:<3} {phase['title']:<28} [{bar(phase['fraction'], 24)}] "
                   f"{phase['fraction'] * 100:5.1f}%   {phase['eta']}")
    out.append("```\n")

    out.append("## Phases\n")
    for phase in computed["phases"]:
        out.append(f"### {phase['id']} — {phase['title']} · {phase['fraction'] * 100:.0f}%\n")
        out.append(f"*{phase['spec']}* — **{phase['eta']}**")
        if phase.get("next"):
            out.append(f"\nNext: {phase['next']}" if phase["fraction"] < 1 else "")
        out.append("")
        out.append("| Item | Class | Status | Notes |")
        out.append("|---|---|---|---|")
        for item in phase["items"]:
            note = item.get("note", "")
            if item["status"] == "blocked":
                note = "WAITING ON A DECISION" + (f" — {note}" if note else "")
            out.append(f"| {item['name']} | {item['class']} — {CLASS_LABEL[item['class']]} | "
                       f"{STATUS_LABEL.get(item['status'], item['status'])} | {note} |")
        out.append("")

    out.append("## Requirements that will not be built as written\n")
    out.append("Each of these is a permanent decision, not a backlog item: the technique it "
               "would need is one this project rules out (injection, hooking, patching, or "
               "constant screen capture). The closest possible treatment is named instead.\n")
    out.append("| Specification | Why it cannot be done, and what is done instead |")
    out.append("|---|---|")
    for row in data["out_of_scope"]:
        out.append(f"| {row['spec']} | {row['why']} |")
    out.append("")

    out.append("## Specification coverage at a glance\n")
    out.append("| Specification | Phase | Class | Status |")
    out.append("|---|---|---|---|")
    for row in data["spec_map"]:
        out.append(f"| {row['section']} | {row['phase']} | {row['class']} | "
                   f"{STATUS_LABEL.get(row['status'], row['status'])} |")
    out.append("")

    out.append("## Acceptance test (§45)\n")
    out.append("| Area | Row | Status | Note |")
    out.append("|---|---|---|---|")
    for row in data["acceptance"]:
        out.append(f"| {row['area']} | {row['row']} | {STATUS_LABEL.get(row['status'], row['status'])} | "
                   f"{row.get('note', '')} |")
    out.append("")
    out.append(f"Packaging and distribution: **{data['packaging']['status']}** — {data['packaging']['note']}\n")
    out.append("---\n")
    out.append("Regenerate with `python3 tools/progress.py`; view it in a browser with "
               "`python3 tools/progress.py --serve`.\n")
    return "\n".join(out)


def html_document(data: dict, computed: dict, stamp: str) -> str:
    e = html.escape
    css_status = {
        "done": ("#7fd6a5", "rgba(127,214,165,.14)"),
        "partial": ("#8fb8ff", "rgba(143,184,255,.14)"),
        "todo": ("#c8ccd8", "rgba(200,204,216,.10)"),
        "blocked": ("#ffcf8f", "rgba(255,207,143,.16)"),
        "impossible": ("#ff9f9f", "rgba(255,159,159,.12)"),
        "user": ("#c9a7ff", "rgba(201,167,255,.16)"),
    }

    def chip(status: str) -> str:
        fg, bg = css_status.get(status, ("#c8ccd8", "rgba(200,204,216,.10)"))
        return (f'<span class="chip" style="color:{fg};background:{bg};border-color:{fg}33">'
                f'{e(STATUS_LABEL.get(status, status))}</span>')

    parts: list[str] = []
    a = parts.append
    a("<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>")
    a("<meta name='viewport' content='width=device-width,initial-scale=1'>")
    a("<title>Azy Skin — implementation progress</title><style>")
    a("""
:root{--bg:#16171b;--bg2:#1b1d22;--surface:rgba(255,255,255,.028);--surface2:rgba(255,255,255,.05);
--line:rgba(255,255,255,.075);--line2:rgba(255,255,255,.13);--text:#e7e9ef;--muted:#9aa0ad;
--accent:#7f9dff;--accent2:#a684ff;--done:#7fd6a5}
*{box-sizing:border-box}
body{margin:0;background:
 radial-gradient(1200px 700px at 12% -12%, rgba(127,157,255,.10), transparent 62%),
 radial-gradient(1100px 700px at 108% 118%, rgba(166,132,255,.09), transparent 60%),
 linear-gradient(180deg,#171a1f,#121317 62%,#101115);
 color:var(--text);font:14px/1.55 "Segoe UI",Inter,system-ui,-apple-system,sans-serif;
 min-height:100vh;padding:34px 22px 60px}
.wrap{max-width:1080px;margin:0 auto}
h1{font-size:22px;font-weight:600;letter-spacing:.2px;margin:0 0 6px}
h1 span{color:var(--accent)}
.sub{color:var(--muted);font-size:12.5px;margin-bottom:22px}
.sub code{color:#c9ccd6;background:var(--surface2);border:1px solid var(--line);border-radius:5px;padding:1px 5px}
.card{background:linear-gradient(180deg,var(--surface2),var(--surface));border:1px solid var(--line);
 border-radius:14px;padding:18px 20px;margin-bottom:14px;box-shadow:0 18px 40px -28px rgba(0,0,0,.9)}
.card.hi{border-color:var(--line2);background:linear-gradient(180deg,rgba(127,157,255,.07),var(--surface))}
.overall{display:flex;align-items:baseline;gap:14px;flex-wrap:wrap;margin-bottom:10px}
.overall .num{font-size:38px;font-weight:650;letter-spacing:-.5px;
 background:linear-gradient(92deg,#bcd0ff,#d9c4ff);-webkit-background-clip:text;background-clip:text;color:transparent}
.overall .lbl{color:var(--muted);font-size:12.5px}
.track{position:relative;height:12px;border-radius:9px;background:rgba(255,255,255,.055);
 border:1px solid var(--line);overflow:hidden}
.track .fill{position:absolute;inset:0 auto 0 0;border-radius:9px;
 background:linear-gradient(92deg,#5f7fe6,#9a7cf0 62%,#b79bff);
 box-shadow:0 0 18px -2px rgba(140,150,255,.5)}
.track.small{height:7px}
.grid{display:grid;grid-template-columns:1fr;gap:12px}
.ph{display:grid;grid-template-columns:1fr auto;gap:6px 16px;align-items:baseline}
.ph .t{font-weight:600;font-size:15px}
.ph .pct{font-variant-numeric:tabular-nums;color:#cdd3e2;font-size:13px}
.ph .meta{grid-column:1/-1;color:var(--muted);font-size:12px}
.ph .next{grid-column:1/-1;font-size:12.5px;color:#b9c2d6}
.bar{margin:4px 0 10px}
table{border-collapse:collapse;width:100%;font-size:12.5px}
th,td{text-align:left;padding:7px 9px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--muted);font-weight:500;text-transform:uppercase;font-size:10.5px;letter-spacing:.7px}
td.n{color:var(--muted)}
.chip{display:inline-block;font-size:10.5px;padding:1px 7px;border-radius:999px;border:1px solid;
 white-space:nowrap;letter-spacing:.3px}
.cls{display:inline-block;min-width:17px;text-align:center;font-weight:600;font-size:11px;
 border-radius:5px;padding:0 5px;border:1px solid var(--line2);color:#cfd5e4}
.cls.A{color:#7fd6a5}.cls.B{color:#8fb8ff}.cls.C{color:#ffcf8f}.cls.D{color:#ff9f9f}
details{margin-top:6px}
summary{cursor:pointer;color:var(--muted);font-size:12.5px}
summary:hover{color:#cfd5e4}
.warn{border-left:3px solid #ffcf8f}
ul.tight{margin:6px 0 0 18px;padding:0}
ul.tight li{margin:3px 0;color:#c3c9d7;font-size:12.5px}
.foot{color:var(--muted);font-size:11.5px;margin-top:26px;text-align:center}
.foot code{color:#c9ccd6}
""")
    a("</style></head><body><div class='wrap'>")
    a(f"<h1>Azy Skin <span>progress</span></h1>")
    a(f"<div class='sub'>Against the Complete Implementation Specification (50 sections) · "
      f"shipped build <b>{e(data['shipped'])}</b> · generated {e(stamp)}</div>")

    overall = computed["overall"]
    a("<div class='card hi'>")
    a("<div class='overall'>")
    a(f"<div class='num'>{overall * 100:.0f}%</div>")
    a(f"<div class='lbl'>weighted across all phases · remaining work ≈ <b>{e(computed['eta_total'])}</b>"
      f"<br>Class D rows (which need injection) are excluded from the number and listed below</div>")
    a("</div>")
    a(f"<div class='track'><div class='fill' style='width:{overall * 100:.1f}%'></div></div>")
    a("</div>")

    a("<div class='card'><div class='grid'>")
    for phase in computed["phases"]:
        pct = phase["fraction"] * 100
        a("<div>")
        a("<div class='ph'>")
        a(f"<div class='t'>{e(phase['id'])} · {e(phase['title'])}</div>")
        a(f"<div class='pct'>{pct:.0f}%</div>")
        a("</div>")
        a(f"<div class='bar'><div class='track small'><div class='fill' style='width:{pct:.1f}%'></div></div></div>")
        a(f"<div class='meta'>{e(phase['spec'])} · {e(phase['eta'])}</div>")
        if pct < 100 and phase.get("next"):
            a(f"<div class='next'>Next: {e(phase['next'])}</div>")
        a("<details><summary>")
        cnt = {s: sum(1 for i in phase["items"] if i["status"] == s) for s in
               ("done", "partial", "todo", "blocked", "impossible")}
        a(" · ".join(f"{v} {STATUS_LABEL[k]}" for k, v in cnt.items() if v))
        a("</summary><table><tbody>")
        for item in phase["items"]:
            note = html.escape(item.get("note", ""))
            if item["status"] == "blocked":
                note = "<b>Waiting on a decision</b>" + (f" — {note}" if note else "")
            a(f"<tr><td><span class='cls {item['class']}'>{item['class']}</span> {e(item['name'])}"
              f"<div class='n'>{note}</div></td>"
              f"<td style='white-space:nowrap'>{chip(item['status'])}</td></tr>")
        a("</tbody></table></details>")
        a("</div>")
    a("</div></div>")

    a("<div class='card warn'><div class='t' style='font-weight:600;font-size:15px;margin-bottom:6px'>"
      "Requirements that will not be built as written</div>")
    a("<div class='sub' style='margin:0 0 10px'>Permanent decisions, not backlog: each one would need a "
      "technique this project rules out (injection, hooking, patching, constant screen capture). "
      "The closest possible treatment is named instead.</div><table><tbody>")
    for row in data["out_of_scope"]:
        a(f"<tr><td style='width:34%'>{e(row['spec'])}</td><td class='n'>{e(row['why'])}</td></tr>")
    a("</tbody></table></div>")

    a("<div class='card'><div class='t' style='font-weight:600;font-size:15px;margin-bottom:6px'>"
      "Acceptance test (§45)</div><table><thead><tr><th>Area</th><th>Row</th><th>Status</th>"
      "<th>Note</th></tr></thead><tbody>")
    for row in data["acceptance"]:
        a(f"<tr><td>{e(row['area'])}</td><td>{e(row['row'])}</td><td>{chip(row['status'])}</td>"
          f"<td class='n'>{e(row.get('note', ''))}</td></tr>")
    a("</tbody></table>")
    a(f"<div class='sub' style='margin:10px 0 0'>Packaging and distribution: <b>{e(data['packaging']['status'])}</b>"
      f" — {e(data['packaging']['note'])}</div></div>")

    a("<div class='card'><div class='t' style='font-weight:600;font-size:15px;margin-bottom:6px'>"
      "Specification coverage</div><table><thead><tr><th>Specification</th><th>Phase</th>"
      "<th>Class</th><th>Status</th></tr></thead><tbody>")
    for row in data["spec_map"]:
        a(f"<tr><td>{e(row['section'])}</td><td class='n'>{e(row['phase'])}</td>"
          f"<td><span class='cls {row['class'][0]}'>{e(row['class'])}</span></td>"
          f"<td>{chip(row['status'])}</td></tr>")
    a("</tbody></table></div>")

    legend = ("<div class='card'><div class='t' style='font-weight:600;font-size:15px;margin-bottom:8px'>"
              "How to read this</div><ul class='tight'>"
              "<li><b>A — native, shipped.</b> Uses documented Windows APIs; every call reversible.</li>"
              "<li><b>B — native, planned.</b> Same rules, not written yet.</li>"
              "<li><b>C — closest possible.</b> The effect is reachable; the widget itself belongs to "
              "Premiere and cannot be restyled from outside. A static, click-through region treatment is "
              "the honest substitute.</li>"
              "<li><b>D — not attempted.</b> Needs injection, hooking or patching. Excluded from the "
              "progress number, shown anyway so nothing is hidden.</li>"
              "<li>Percentages are weighted by effort, not by counting rows.</li>"
              "</ul></div>")
    a(legend)

    a(f"<div class='foot'>Generated by <code>tools/progress.py</code> from "
      f"<code>docs/progress.json</code> · {e(stamp)}<br>"
      f"Feasibility detail: <code>docs/FEASIBILITY.md</code> · techniques: "
      f"<code>docs/TECHNIQUES.md</code></div>")
    a("</div></body></html>")
    return "".join(parts)


VALID_STATUS = {"done", "partial", "todo", "blocked", "impossible", "user"}
VALID_CLASS = {"A", "B", "C", "D"}


def validate(data: dict) -> list[str]:
    """Cheap guard against a typo silently counting as zero progress."""
    problems: list[str] = []
    for phase in data["phases"]:
        for item in phase["items"]:
            if item["status"] not in VALID_STATUS:
                problems.append(f"{phase['id']}: unknown status {item['status']!r} ({item['name']})")
            if item["class"] not in VALID_CLASS:
                problems.append(f"{phase['id']}: unknown class {item['class']!r} ({item['name']})")
    for row in data["spec_map"]:
        for cls in row["class"].split("/"):
            if cls not in VALID_CLASS:
                problems.append(f"spec_map: unknown class {cls!r} ({row['section']})")
        if row["status"] not in VALID_STATUS:
            problems.append(f"spec_map: unknown status {row['status']!r} ({row['section']})")
    for row in data["acceptance"]:
        if row["status"] not in VALID_STATUS:
            problems.append(f"acceptance: unknown status {row['status']!r} ({row['row']})")
    return problems


def normalize(text: str) -> str:
    """The timestamp is the only volatile field, so it is ignored when checking
    that the generated files are up to date with the data."""
    return re.sub(r"\d{4}-\d\d-\d\d \d\d:\d\d UTC", "<stamp>", text)


def compute(data: dict) -> dict:
    phases = []
    for phase in data["phases"]:
        fraction, weight, counted = phase_progress(phase)
        phases.append({**phase, "fraction": fraction, "weight": weight, "counted": counted})

    total = sum(p["weight"] for p in phases)
    earned = sum(p["weight"] * p["fraction"] for p in phases)
    overall = earned / total if total else 0.0

    # A session is one exchange of this kind: implement, build, verify, hand back.
    # The only unknown is how long testing on the user's machine takes.
    sessions = 0.0
    for phase in phases:
        if phase["fraction"] >= 0.999:
            continue
        numbers = [float(x) for x in re.findall(r"\d+(?:\.\d+)?", phase.get("eta", ""))]
        if numbers:
            # A range ("2-3 sessions") is counted at its upper bound: an estimate
            # that turns out optimistic is worse than one that turns out slow.
            sessions += max(numbers)
    eta_total = f"{sessions:.0f} work sessions" if sessions else "nothing scheduled"
    return {"phases": phases, "overall": overall, "eta_total": eta_total}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--serve", action="store_true", help="serve docs/progress.html after writing it")
    parser.add_argument("--check", action="store_true",
                        help="verify the generated files match the data; write nothing")
    parser.add_argument("--port", type=int, default=8111)
    args = parser.parse_args()

    data = json.loads(DATA.read_text(encoding="utf-8"))
    problems = validate(data)
    if problems:
        for problem in problems:
            print(f"progress data: {problem}", file=sys.stderr)
        return 1

    computed = compute(data)
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rendered = {
        MD: markdown(data, computed, stamp),
        HTML: html_document(data, computed, stamp),
    }

    if args.check:
        for path, text in rendered.items():
            if not path.exists():
                print(f"missing: {path.relative_to(ROOT)} (run tools/progress.py)", file=sys.stderr)
                return 1
            if normalize(path.read_text(encoding="utf-8")) != normalize(text):
                print(f"out of date: {path.relative_to(ROOT)} (run tools/progress.py)",
                      file=sys.stderr)
                return 1
        print(f"progress board: in sync at {computed['overall'] * 100:.1f}%")
        return 0

    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")

    print(f"overall {computed['overall'] * 100:.1f}% (remaining ≈ {computed['eta_total']})")
    for phase in computed["phases"]:
        print(f"  {phase['id']} {phase['title']:<28} {phase['fraction'] * 100:5.1f}%  {phase['eta']}")
    print("wrote docs/PROGRESS.md and docs/progress.html")

    if args.serve:
        serve(args.port)
    return 0


def serve(port: int) -> None:  # pragma: no cover - interactive
    """Serves the board at / (and nothing else). Binds 0.0.0.0, not loopback, so a
    preview proxy in front of the sandbox can reach it."""
    import http.server
    import socketserver

    documents = ROOT / "docs"

    class Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *a, **k):
            super().__init__(*a, directory=str(documents), **k)

        def do_GET(self):  # noqa: N802 - the name is fixed by the base class
            if self.path in ("/", "/index.html"):
                self.path = "/progress.html"
            return super().do_GET()

        def log_message(self, *a):  # quiet: this is a viewer, not a server
            return

    socketserver.ThreadingTCPServer.allow_reuse_address = True
    with socketserver.ThreadingTCPServer(("0.0.0.0", port), Handler) as httpd:
        print(f"progress board: http://localhost:{port}/progress.html")
        httpd.serve_forever()


if __name__ == "__main__":
    sys.exit(main())
